from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

def generate_pdf(results, profit_table, user):
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)

    c.setFont("Helvetica-Bold", 14)
    c.drawString(200, 800, "Freight Calculator Report")

    c.setFont("Helvetica", 10)
    c.drawString(50, 780, f"Generated by: {user}")
    c.drawString(50, 765, "----------------------------------------------")

    y = 740
    for _, row in results.iterrows():
        c.drawString(50, y, f"{row['Keterangan']}: {round(row['Hasil'], 2)}")
        y -= 15

    y -= 20
    c.drawString(50, y, "Profit Table:")
    y -= 15
    for _, row in profit_table.iterrows():
        c.drawString(50, y, f"{row['Profit %']}% | Revenue: {int(row['Revenue'])} | Net: {int(row['Net Profit'])}")
        y -= 12
        if y < 50:
            c.showPage()
            y = 800

    c.save()
    pdf = buffer.getvalue()
    buffer.close()
    return pdf
