[firebase]
type = "service_account"
project_id = "freight-demo2"
private_key_id = "4b1e74b94d73d6977c920311506b25c5bec2995e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDYdmlSP1HbjGNB
mKRXzIUzT7uvlcKIw9QUJAu7LozTCLIAPmzkDr7KralvyL4lPsvCGeOa8gNvF+QI
... (lanjut sampai akhir)
K54I57RwFUyiUAxEI08BuKE=
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-xxxx@freight-demo2.iam.gserviceaccount.com"
client_id = "105882183393067904343"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40freight-demo2.iam.gserviceaccount.com"
